export const
  CHANGE_TO_FAHRENHEIT = "CHANGE_TO_FAHRENHEIT",
  CHANGE_TO_CELSIUS = "CHANGE_TO_CELSIUS",
  CHANGE_TO_LOW_ACTIVITY = "CHANGE_TO_LOW_ACTIVITY",
  CHANGE_TO_HIGH_ACTIVITY = "CHANGE_TO_HIGH_ACTIVITY";